package Entities;
// Generated Dec 10, 2018 1:14:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Filieres generated by hbm2java
 */
public class Filieres  implements java.io.Serializable {


     private String code;
     private String nom;
     private Set eleves = new HashSet(0);

    public Filieres() {
    }

	
    public Filieres(String code, String nom) {
        this.code = code;
        this.nom = nom;
    }
    public Filieres(String code, String nom, Set eleves) {
       this.code = code;
       this.nom = nom;
       this.eleves = eleves;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getEleves() {
        return this.eleves;
    }
    
    public void setEleves(Set eleves) {
        this.eleves = eleves;
    }




}


