package Entities;
// Generated Dec 10, 2018 1:14:15 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String login;
     private String password;

    public Users() {
    }

    public Users(String login, String password) {
       this.login = login;
       this.password = password;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


